name: flutter_mqtt_chat_sample
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^9.6.5
  flutter_bloc: 7.2.0
  equatable: ^2.0.3
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  flutter_emoji: ^2.4.0
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  font_awesome_flutter: ^9.2.0
  path: ^1.8.1
  flutter_image_compress: ^1.0.0-nullsafety
  flutter_neumorphic: ^3.2.0


  cupertino_icons: ^1.0.2


  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  
